import { VibeCard, UserProfile, Message } from './types';

export const INITIAL_VIBE_CARDS: VibeCard[] = [
  {
    id: '1',
    title: 'Cyberpunk Nights: Tokyo Motion',
    category: 'photography',
    categoryLabel: 'Photography',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC2i1AUdzK051Crs8S8QBvkjLKwV_BTGTZrSlQCxvuMPfQ2i3zvzM7fz7FTFtujiiZTE7Q-RoKZSBb83IrPmah9U-w6xPnpS-Yr02yltX-wyHgOoNSnDBrRhU0u4AeKSlh4xD7w2mjXUfyECtfC9JJzw-VEHy5LSvCNpzNcEH_AkahjQaUSkmuOTkE2cL0PXPGZADjNvRNvp5tKMCufIC-0dlgpY_HVMKjpywpkyqtV7RAu8bKJ7JgMFHrh6roQM8YwDn7fEbpwOwQ',
    authorName: 'Lucas Vibe',
    authorHandle: 'lucas_vibe',
    likes: 1240,
    comments: 48,
    hasLiked: true,
    hasBookmarked: false,
    description: 'A cinematic long-exposure photograph of a bustling neon-lit Tokyo street at night. The image captures vibrant streaks of pink and cyan light from passing vehicles, contrasting against the deep midnight blue of the urban architecture.',
  },
  {
    id: '2',
    title: 'Iris: The Neural Muse',
    category: 'ai_art',
    categoryLabel: 'AI Art',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCC2hkkchBoNQhU0IaVBVKs0WbCiFpMSOMtQpRvY_txavVbe8dFgXDO0CZZZWfoQtwA-14-GucA2dS3bJaVVK-nWp_zw67luXI05fJqyIpYhluSxEeWgyhmzFzZtfI2RAO0whAglVYVOI3vx4bP8EsknLSS03EUzUl7_YscCXqcKPR0XBXmz7DIioitieo8k2_BSe0vLz0f2xTCuj6F9MKNP6MVM73PIOaYU5y-uSZVd3QvYmksk1bV4T2vgoCom66P5nPq5NKeQy8',
    authorName: 'Nexus Creator',
    authorHandle: 'nexus_creator',
    likes: 856,
    comments: 12,
    hasLiked: false,
    hasBookmarked: true,
    description: 'An ethereal AI-generated portrait of a digital goddess composed of iridescent crystalline structures and glowing fiber-optic hair, set against deep midnight violet bioluminescent dust.',
  },
  {
    id: '3',
    title: 'Optimizing Glassmorphism for Three.js',
    category: 'coding',
    categoryLabel: 'Coding',
    image: '', // Represents text/code snippet card
    authorName: 'Aiden Dev',
    authorHandle: 'aiden_codes',
    likes: 74,
    comments: 5,
    hasLiked: false,
    hasBookmarked: false,
    description: 'A comprehensive performance optimization guide for glassmorphic shader materials in WebGL and Three.js environments, achieving stable 60fps on mobile browser setups.',
  },
  {
    id: '4',
    title: 'Winter at Altitude 4000',
    category: 'travel',
    categoryLabel: 'Travel',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA6ra0tFdvHJM__hhKf1CTBrrQ5n3WXlmO76Dfzz8lY1hOxXZLCyqlwwZWUyoc13ZQs7TJFs3UupcHHqSGAafAdC7Bl7vI530T07R3zRnLnmLDNZIrrNf51A4oMMWikt0QRpBUBZRRzdGJ1tzhVJUiXLfwa7-aZXKJ0uWXb7rR8acj7Xu9s3ENKtXq-UBdHyZ5m1Zmx6SFJFFno7yQvh7krYNlcd6BEAr04gq7u0f0vJCErAaL1Hy8C0hX5fpxnBrnZvvWegFmYyJI',
    authorName: 'Chloe Alpine',
    authorHandle: 'chloe_travels',
    likes: 421,
    comments: 29,
    hasLiked: false,
    hasBookmarked: false,
    location: 'Zermatt, CH',
    description: 'Exploring the most remote luxury hubs where futuristic architecture merges with the vertical alpine void, nestled high in the Swiss Alps.',
  },
  {
    id: '5',
    title: 'Molecular Echoes: The Neon Fusion',
    category: 'food',
    categoryLabel: 'Food',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD7ye6ospgkKtPtOuUw9LRAg2HRKczkMRcBwEu7J9u-ybs_OldVkyVz--IU7clNsxhSv7N8jZhvqbu-PJuGNp_BpI0KAeT3Pp2S0Ei-8K20HirWuuDfV3Qeh6VQekeCoxMG8n-NUJR5TRSJb8wCYCYY2Oiw97Un5BzitwtEq_dD-r2xCaZQTjb40w6vRwqBAMuqSa_wJdsvhYMAtAl4-1E7UYd43kFHM5mEYdCXm7jfFBZtR5tiMFv5YJx_FFB3BmgWyitJd4QzQsI',
    authorName: 'Chef Nova',
    authorHandle: 'chef_nova_ai',
    likes: 342,
    comments: 19,
    hasLiked: false,
    hasBookmarked: false,
    tags: ['Fusion', 'Fine Dining'],
    description: 'An ultra-modern fine dining dessert presentation on a matte black ceramic plate. A spherical white chocolate shell is drizzled with vibrant magenta dragon fruit reduction, edible gold, and micro-greens.',
  },
  {
    id: '6',
    title: 'Metro-Pulse: Level 240',
    category: 'ai_art',
    categoryLabel: 'AI Art',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDeTpRNfIkEIxF5JiQ6dDmE7c8hls2z2KSmXFGDnNAEsSTkJLytPigxkNzigQAWSEzApfFAeMfP3ejTiRs_wyI8s7axly3ciLmEWBMjSXc6uXQG7C_eYrD_pO-3j3T3FAiAYQfju3oqeHJMD8lpdfcaznCWACwtjj23fgA_rf9X_wYN4QFQZXp3nJU31MdF55qG-szxXQo2_bQ9NzgaxcHPicVfJA9wDT4vbTWEICmm6zDds0v0JTyVBQ11JhvatCQtARi5R0_vKwo',
    authorName: 'Vapor Dreamer',
    authorHandle: 'vapor_dreamer',
    likes: 912,
    comments: 31,
    hasLiked: false,
    hasBookmarked: false,
    description: 'A sprawling futuristic cityscape seen from above, with floating transport vessels weaving through massive obsidian skyscrapers. Layered in neon advertisements of pink, purple, and blue.',
  },
  {
    id: '7',
    title: 'Chronos Mechanism',
    category: 'photography',
    categoryLabel: 'Photography',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAP7kzNFxUKkWLWZYNGgqovC6y_UAtaH2YpjqLzUqC_-jiKFblMm-PeFC0KWSHrKuWF_9CN913FRAyL6uEcIxExS1uRlwojm4oLo9CakMGdrSzzNP3tel1D3K7clkTJu5pVOPHTagCpWkumEbJC78J6K85bH_G9fX4H9A-sV_wxiPtQb17fHWvIb1TDOZFN54YCR2X3JFoPDiVgUfn86MQsRvGyZZ-hKqyGMdl8I1y215GMmglzeE1a2ZpDS33WCH4uUja82AqsI50',
    authorName: 'Horology Lens',
    authorHandle: 'horology_lens',
    likes: 1105,
    comments: 55,
    hasLiked: false,
    hasBookmarked: false,
    description: 'A macro photograph of an expensive mechanical watch movement, showing intricate gears and rubies. The metallic surfaces are polished to a mirror finish, reflecting soft purple ambient light.',
  },
];

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Alex Rivera',
  handle: 'neon_nomad',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBu5Cy-F6cQ-G4lTOpty_9slgYMc99mkWVoZGdoP8xD41oy-CpFSBkU4G-bOnzh7AkCazbzGsSXpNAdTIMn-KoS3eTLQTgl6trL9DawDpNICu6SQaBys_-lElojOUPp7i2nrdpr4OqVK7Gw9Jk4rnX7krilu6NlfakmRPnG_zVBO_9tQc2wmbs3Wo8tdK0W8vkLQMi8JvBciki1Pf1hMBYQH-kGkvwyywYDwC1sisvxxUyRPR7ufRRLG2Z64QeUPGtPnXkx6TJIKj0',
  vibeScore: 88,
  vibeStatus: 'Neon Nomad',
  bio: 'Exploring the intersection of brutalist architecture, vaporwave aesthetics, and high-fidelity machine dreams. Finding beauty in neon shadows.',
  achievements: [
    { id: '1', title: 'Smooth Talker', icon: 'MessageSquareText', color: '#fface8', locked: false },
    { id: '2', title: 'Trend Setter', icon: 'TrendingUp', color: '#00dbe9', locked: false },
    { id: '3', title: 'Vibe Architect', icon: 'Lock', color: '#303444', locked: true },
  ],
  metrics: {
    charisma: 92,
    wit: 74,
    authenticity: 85,
  },
};

export const INITIAL_CHAT_HISTORY: Message[] = [
  {
    id: 'm1',
    sender: 'ai',
    text: 'Welcome back! Your current Vibe Score is peaking at 88%. Ready to optimize your digital presence today? How can I assist you?',
    timestamp: '12:00 PM',
    options: ['Improve my Bio', 'Generate Icebreaker', 'Compatibility Report'],
  },
  {
    id: 'm2',
    sender: 'user',
    text: 'Hey Nexus! Help me with an icebreaker for someone who loves vaporwave and minimalist architecture.',
    timestamp: '12:01 PM',
  },
  {
    id: 'm3',
    sender: 'ai',
    text: "Ooh, a classic aesthetic match! Here's a high-impact opener:",
    timestamp: '12:02 PM',
    quote: '"If our vibe was a render, would it be a low-poly sunset or a brutalist masterpiece with neon lighting? Either way, I think the composition is perfect."',
    options: ['Tailor for Tinder', 'Tailor for LinkedIn', 'Try another vibe'],
  },
];
